name: protopos
description: "Talasi POS membantu Anda mengelola transaksi penjualan, stok, dan laporan bisnis dengan cepat dan mudah. Cocok untuk toko, kafe, dan usaha ritel Anda."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  http: ^1.0.0
  shared_preferences: ^2.1.1
  rounded_loading_button_plus: ^3.0.1
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.12.1
  google_fonts: ^6.1.0
  icons_plus: ^4.0.0
  get: ^4.6.6
  flutter_native_splash: ^2.3.0
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  esc_pos_utils_plus: ^2.0.4
  flutter_thermal_printer: ^1.2.4
  permission_handler: ^12.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_native_splash:
  color: "#FFFFFF"              # white
  image: assets/logo/logo_400.png
  color_dark: "#FFFFFF"         # white for dark mode
  image_dark: assets/logo/logo_400.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Lock.svg
    - assets/icons/User.svg
    - assets/icons/user.png
    - assets/logo/logo_400.png
    - assets/logo/icon_app.png
    - assets/logo/splash_logo.png
    - assets/splash_logo.png
